version: "2.1"

services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file: .env
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - ${SERVERPORT:-51820}:${SERVERPORT:-51820}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always

